# Programming Assignment_8

# 1. Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np

In [7]:
np.mat([1,2,3,4])

matrix([[1, 2, 3, 4]])

In [16]:
mat1=np.matrix([2,4,6,8]).reshape(2,2)

In [21]:
mat2=np.matrix([1,2,3,4]).reshape(2,2)

In [22]:
mat1+mat2

matrix([[ 3,  6],
        [ 9, 12]])

# 2. Write a Python Program to Multiply Two Matrices?

In [23]:
mat1@mat2

matrix([[14, 20],
        [30, 44]])

# 3. Write a Python Program to Transpose a Matrix?

In [25]:
mat1

matrix([[2, 4],
        [6, 8]])

In [24]:
mat1.T

matrix([[2, 6],
        [4, 8]])

# 4. Write a Python Program to Sort Words in Alphabetic Order?

In [89]:
stri="Enter something for me"
words=stri.split()
words
words.sort()
for i in words:
    print(i)

Enter
for
me
something


# 5.Write a Python Program to Remove Punctuation From a String?

In [114]:
punctuation='''!()-[]{};:'"\,<>./?@#$%^&*_~'''
word='I am pursuing MBA, What about you?'
words=""
for i in word:
    if i not in punctuation:
        words=words+i
print(words)

I am pursuing MBA What about you
